SELECT *
FROM SEMANTIC_VIEW (
    SNOWGHOST_BREAKERS_ANALYTICS
    DIMENSIONS GHOSTS.GHOST_NAME, GHOSTS.THREAT_LEVEL, GHOSTS.GHOST_TYPE
    WHERE GHOSTS.STATUS = 'Active'
);

--     METRICS GHOST_SIGHTINGS

SELECT *
FROM SEMANTIC_VIEW (
    SNOWGHOST_BREAKERS_ANALYTICS
    FACTS GHOST_SIGHTINGS.EMF_READING, GHOST_SIGHTINGS.PARANORMAL_ACTIVITY_LEVEL
    DIMENSIONS GHOST_SIGHTINGS.DESCRIPTION, GHOST_SIGHTINGS.LOCATION_NAME, GHOST_SIGHTINGS.WITNESS_NAME
);
